[package]
name = "parser_configuration"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2018"
authors = ["Furazhki Dimitriy furagkin678@gmail.com"]
discription = "Library for parsing information from temporary files."

[dependencies]
